# port = 18889 (default: 18889)
# host = "0.0.0.0 (default: 127.0.0.1)"
# secret = "your webhook secret"
# logfile = "path to logfile (default: stdout)" 
# pidfile = "path to pidfile"

[[hook]]
event = "push"
command = "/path/to/sh"
branch = "feature/*"

[[hook]]
event = "pull_request"
command = "/path/to/sh"
# call Status API (See: https://developer.github.com/v3/repos/statuses/#create-a-status)
access_token = "your access token"
include_actions = [ "opened", "reopened" ]
# exclude_actions = [ "closed", "unlabeled" ]
